bug:
  name: Bug Report
  about: Report an issue with the project
  labels: ["bug"]
  body:
    - type: markdown
      attributes:
        value: |
          Thanks for reporting an issue! Please provide as much detail as possible.
    - type: input
      id: title
      attributes:
        label: "Issue Title"
        description: "A concise, descriptive title for the bug."
        placeholder: "e.g., Dataflow pipeline fails with OutOfMemory error on large datasets"
      validations:
        required: true
    - type: dropdown
      id: severity
      attributes:
        label: "Severity"
        description: "How critical is this issue?"
        options:
          - "Critical"
          - "Major"
          - "Minor"
          - "Cosmetic"
        default: "Major"
      validations:
        required: true
    - type: textarea
      id: description
      attributes:
        label: "Description"
        description: "Detailed description of the bug."
        placeholder: |
          What is the expected behavior?
          What is the actual behavior?
          How can we reproduce this bug?
    - type: textarea
      id: steps
      attributes:
        label: "Steps to Reproduce"
        description: "Provide clear, step-by-step instructions to reproduce the issue."
        placeholder: |
          1. Go to...
          2. Click on...
          3. Observe...
    - type: textarea
      id: environment
      attributes:
        label: "Environment"
        description: "Please provide details about your environment (e.g., OS, browser, versions of tools used, Python version)."
        placeholder: |
          - OS:
          - Python version:
          - Tool versions:
    - type: textarea
      id: logs
      attributes:
        label: "Logs (if applicable)"
        description: "Paste any relevant error messages or logs here. Please format them as code blocks."
        placeholder: |
          ```
          Error log goes here...
          ```
    - type: textarea
      id: additional-context
      attributes:
        label: "Additional Context"
        description: "Any other relevant information, screenshots, or context."
